config:
  credentials:                       #section for secrets
    - name: ec_host
      type: host
    - name: ec_user
      type: user
    - name: ec_ssh
      type: ssh

  inventory:
    path: zos_concepts/zos_ping/inventories/inventory.yml                         # inventory config (builds inventory file dynamically)
    # source_system:
    #   hosts:
    #     zos_host:
    #       ansible_host: "{{ lookup('env', 'ec_host') }}"
    #       ansible_user: "{{ lookup('env', 'ec_user') }}"
    # groups:
    #   webservers:
    #     - web
    #   dbservers:
    #     - db
  
  collections:
  # list of collections need to install
    - ibm.ibm_zos_core
  
  ansible_config:
    path: zos_concepts/zos_ping/ansible.cfg

  stages:
    - name: Ping the IMS EC
      description: "Test the ssh connection to IMS EC using ping"
      playbooks:
        - zos_concepts/zos_ping/zos_ping.yaml

      cleanup:
        - zos_concepts/zos_ping/zos_ping.yaml
